# Generated by Django 4.2.8 on 2026-02-16 02:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("goods", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Wishlist",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="物品名称")),
                (
                    "min_price",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="最低价格",
                    ),
                ),
                (
                    "max_price",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="最高价格",
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="需求描述"),
                ),
                (
                    "keywords",
                    models.JSONField(
                        blank=True, default=list, verbose_name="关键词列表"
                    ),
                ),
                (
                    "match_status",
                    models.CharField(
                        choices=[("pending", "待匹配"), ("matched", "已匹配")],
                        default="pending",
                        max_length=20,
                        verbose_name="匹配状态",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="提交时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="wishlists",
                        to="goods.category",
                        verbose_name="品类",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="wishlists",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="用户",
                    ),
                ),
            ],
            options={
                "verbose_name": "心愿单",
                "verbose_name_plural": "心愿单",
                "db_table": "wishlist",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="MatchResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("goods_id", models.IntegerField(verbose_name="物品ID")),
                (
                    "goods_name",
                    models.CharField(max_length=200, verbose_name="物品名称"),
                ),
                (
                    "goods_price",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="物品价格"
                    ),
                ),
                (
                    "similarity_score",
                    models.FloatField(default=0, verbose_name="相似度分数"),
                ),
                (
                    "is_read",
                    models.BooleanField(default=False, verbose_name="是否已读"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="匹配时间"),
                ),
                (
                    "wishlist",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="match_results",
                        to="wishlist.wishlist",
                        verbose_name="心愿单",
                    ),
                ),
            ],
            options={
                "verbose_name": "匹配结果",
                "verbose_name_plural": "匹配结果",
                "db_table": "match_result",
                "ordering": ["-similarity_score"],
            },
        ),
    ]
