# Generated by Django 4.2.8 on 2026-02-16 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Report",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "report_type",
                    models.CharField(
                        choices=[
                            ("fake_info", "虚假物品信息"),
                            ("malicious_chat", "恶意聊天"),
                            ("fraud", "交易欺诈"),
                            ("other", "其他"),
                        ],
                        max_length=20,
                        verbose_name="举报类型",
                    ),
                ),
                ("description", models.TextField(verbose_name="举报描述")),
                (
                    "evidence",
                    models.JSONField(blank=True, default=list, verbose_name="证据图片"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "待处理"),
                            ("processing", "处理中"),
                            ("resolved", "已解决"),
                            ("rejected", "已驳回"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="处理状态",
                    ),
                ),
                (
                    "result",
                    models.TextField(blank=True, null=True, verbose_name="处理结果"),
                ),
                (
                    "handled_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="处理时间"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="提交时间"),
                ),
            ],
            options={
                "verbose_name": "举报信息",
                "verbose_name_plural": "举报信息",
                "db_table": "report",
                "ordering": ["-created_at"],
            },
        ),
    ]
