# Generated by Django 4.2.8 on 2026-02-16 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CreditRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "change_type",
                    models.CharField(
                        choices=[
                            ("evaluation_good", "好评加分"),
                            ("evaluation_bad", "差评扣分"),
                            ("violation", "违规扣分"),
                            ("admin_adjust", "管理员调整"),
                            ("system", "系统调整"),
                        ],
                        max_length=20,
                        verbose_name="变更类型",
                    ),
                ),
                ("change_score", models.IntegerField(verbose_name="变更分值")),
                ("before_score", models.IntegerField(verbose_name="变更前分数")),
                ("after_score", models.IntegerField(verbose_name="变更后分数")),
                ("reason", models.CharField(max_length=500, verbose_name="变更原因")),
                (
                    "related_order_id",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="关联订单ID"
                    ),
                ),
                (
                    "related_report_id",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="关联举报ID"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="变更时间"),
                ),
            ],
            options={
                "verbose_name": "诚信值记录",
                "verbose_name_plural": "诚信值记录",
                "db_table": "credit_record",
                "ordering": ["-created_at"],
            },
        ),
    ]
