# Generated by Django 4.2.8 on 2026-02-16 02:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="品类名称"
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="品类描述"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
            ],
            options={
                "verbose_name": "物品品类",
                "verbose_name_plural": "物品品类",
                "db_table": "category",
            },
        ),
        migrations.CreateModel(
            name="Goods",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="物品名称")),
                ("description", models.TextField(verbose_name="物品描述")),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="价格"
                    ),
                ),
                (
                    "condition",
                    models.CharField(
                        choices=[
                            ("new", "全新"),
                            ("like_new", "几乎全新"),
                            ("good", "良好"),
                            ("fair", "一般"),
                            ("poor", "较差"),
                        ],
                        default="good",
                        max_length=20,
                        verbose_name="新旧程度",
                    ),
                ),
                (
                    "images",
                    models.JSONField(blank=True, default=list, verbose_name="图片列表"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("on_sale", "上架中"),
                            ("off_sale", "已下架"),
                            ("sold", "已售出"),
                        ],
                        default="on_sale",
                        max_length=20,
                        verbose_name="状态",
                    ),
                ),
                (
                    "pickup_location",
                    models.CharField(
                        blank=True, max_length=200, null=True, verbose_name="取货地点"
                    ),
                ),
                ("view_count", models.IntegerField(default=0, verbose_name="浏览次数")),
                (
                    "is_traded",
                    models.BooleanField(default=False, verbose_name="是否已交易"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="发布时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "category",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="goods",
                        to="goods.category",
                        verbose_name="品类",
                    ),
                ),
            ],
            options={
                "verbose_name": "闲置物品",
                "verbose_name_plural": "闲置物品",
                "db_table": "goods",
                "ordering": ["-created_at"],
            },
        ),
    ]
