# Generated by Django 4.2.8 on 2026-02-16 02:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("goods", "0002_initial"),
        ("orders", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="buyer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="buyer_orders",
                to=settings.AUTH_USER_MODEL,
                verbose_name="买家",
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="goods",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="order",
                to="goods.goods",
                verbose_name="物品",
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="seller",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="seller_orders",
                to=settings.AUTH_USER_MODEL,
                verbose_name="卖家",
            ),
        ),
        migrations.AddField(
            model_name="evaluation",
            name="evaluatee",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="received_evaluations",
                to=settings.AUTH_USER_MODEL,
                verbose_name="被评价人",
            ),
        ),
        migrations.AddField(
            model_name="evaluation",
            name="evaluator",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="evaluations",
                to=settings.AUTH_USER_MODEL,
                verbose_name="评价人",
            ),
        ),
        migrations.AddField(
            model_name="evaluation",
            name="order",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="evaluation",
                to="orders.order",
                verbose_name="订单",
            ),
        ),
    ]
